language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script: echo "TEST"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
